#
server:
  port: 9000
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springboot-security-oauth2
  #####################
  #
  #####################
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
